# PENDING Merging and testing workflow file 
name: Waterfall Deployment Dev
run-name: Elastic Beanstalk Deployment Dev
on:
  workflow_dispatch:
  pull_request:
    types:
      - "closed"
    branches:
      - "dev"
jobs:
  deploy:
    name: deploy backend
    runs-on: ubuntu-20.04
    env:
      CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
      - run: yarn install
      - name: Execute application build Script
        run: yarn run build
      - name: Build code bundle
        run: zip distOut.zip -r dist/
      - name: Check Certificate, host variable and keytype
        run: |
          if [ -z "$CERTIFICATE_BASE64" ]; 
          then 
            echo "Certificate is absent";
            exit 1;
          else 
            echo "Certificate Present"; 
          fi;
      - name: Retrieve the secret and decode it to a file
        run: |
          mkdir ~/.ssh
          echo $CERTIFICATE_BASE64 | base64 --decode > ~/.ssh/waterfall-dev.pem
      - name: change permission for key
        run: |
          sudo chmod 600 ~/.ssh/waterfall-dev.pem 
      - name: Add server to know Hosts
        run: |
          ssh-keyscan -t ${{vars.KEYTYPE}} ${{vars.HOST}} >> ~/.ssh/known_hosts
      - name: remove remote files
        run: ssh -i "~/.ssh/waterfall-dev.pem" ubuntu@${{vars.HOST}} 'cd ~/waterfall/; rm -rf dist/ distOut.zip yarn.lock package.json'
      - name: Copy files over at server
        run: scp -r  -i "~/.ssh/waterfall-dev.pem" distOut.zip package.json yarn.lock ubuntu@${{vars.HOST}}:~/waterfall/
      - name: export pm2 and restart pm2 with updated code
        run: ssh -i "~/.ssh/waterfall-dev.pem" ubuntu@${{vars.HOST}} '. /etc/profile; export PATH=$PATH:$HOME/.nvm/versions/node/v18.18.0/bin; cd $HOME/waterfall/ && yarn install && unzip -o distOut.zip && pm2 restart 0'
      - name: clean up
        run: |
          rm distOut.zip && \
          rm ~/.ssh/waterfall-dev.pem
      - name: Completion
        run: echo "Completed"
